
Org-Balance Documentation

* Introduction

  org-balance is an extension of [[http://orgmode.org][Emacs Org mode]] for balancing your resources (time, money, etc) among your various
  projects.  It will tell you when you spend too much or too little on some projects.  It is simple to use but
  flexible.

  It integrates with existing time-tracking and task-closing commands.   The only new thing you need to do is
  set a few goals, and you can then get all kinds of reports.

  In simplest usage, you can put a /goal/ on a subtree, such as:

  goal_clockedtime: at least 3 hours per week

  The goal is for a _rate_: how you spend a resource per time.   By expressing goals as rates you make comparisons
  interchangeable.

  You can then call org-balance commands to show goals that are not being met -- either as a sparse tree in the
  current file, or as an agenda.  The agenda can be sorted, putting most-neglected goals first.

  Note that you can put goals on broad categories of things, as well as on more concrete items.
  You can also give goals relative in terms of other goals, e.g. .3 of parent goal.
  You can even do .3 of actual time spent.

  But you can also look at goals where you spend more time than needed.  This can help you find time
  for goals that are shortchanged.   You can also list goals that _are_ being met, just to pat yourself on the back.

  You can view a summary over any period, and it will be recalculated for that period.

  Besides spent time, you can also track done things.

  org-balance treats uniformly various resources, whether clockedtime, time passed, or resources attached to
  done or closed commands.

  this lets you do things like, show time spent per response received.   See which parts of your projects do
  better for this ratio, and which do worse.  Show agenda sorted by such ratios.
  (and possibly filtered by level.)

* Configuring org-balance preferences
  
  

  

  
  
  
